parameters:
    oauth2.server.class: OAuth2\Server
    oauth2.request.class: OAuth2\HttpFoundationBridge\Request
    oauth2.request_factory.class: OAuth2\HttpFoundationBridge\Request
    oauth2.response.class: OAuth2\HttpFoundationBridge\Response
    oauth2.storage.client_credentials.class: OAuth2\ServerBundle\Storage\ClientCredentials
    oauth2.storage.access_token.class: OAuth2\ServerBundle\Storage\AccessToken
    oauth2.grant_type.client_credentials.class: OAuth2\GrantType\ClientCredentials
services:
    oauth2.server:
        class: %oauth2.server.class%
        arguments:
            storage:
                client_credentials: @oauth2.storage.client_credentials
                access_token: @oauth2.storage.access_token
    oauth2.request:
        class: %oauth2.request.class%
        factory_class: %oauth2.request_factory.class%
        factory_method: createFromRequest
        scope: request
        arguments:
            request: @request
    oauth2.response:
        class: %oauth2.response.class%
    oauth2.storage.client_credentials:
        class: %oauth2.storage.client_credentials.class%
        arguments:
            em: @doctrine.orm.entity_manager
    oauth2.storage.access_token:
        class: %oauth2.storage.access_token.class%
        arguments:
            em: @doctrine.orm.entity_manager
    oauth2.grant_type.client_credentials:
        class: %oauth2.grant_type.client_credentials.class%
        arguments:
            storage: @oauth2.storage.client_credentials